server:
  port: 8080

spring:
  application:
    name: clusterizer

etcd:
  endpoint: "http://127.0.0.1:2379"

logging:
  level:
    org.springframework.messaging.rsocket: TRACE
    io.rsocket: DEBUG

docker:
  connections:
    local:
      target:
        type: local
        path: "unix:///var/run/docker.sock"
